// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pepsighan/graftini_backend/internal/pkg/ent/earlyaccess"
	"github.com/pepsighan/graftini_backend/internal/pkg/ent/predicate"
)

// EarlyAccessUpdate is the builder for updating EarlyAccess entities.
type EarlyAccessUpdate struct {
	config
	hooks    []Hook
	mutation *EarlyAccessMutation
}

// Where adds a new predicate for the EarlyAccessUpdate builder.
func (eau *EarlyAccessUpdate) Where(ps ...predicate.EarlyAccess) *EarlyAccessUpdate {
	eau.mutation.predicates = append(eau.mutation.predicates, ps...)
	return eau
}

// SetEmail sets the "email" field.
func (eau *EarlyAccessUpdate) SetEmail(s string) *EarlyAccessUpdate {
	eau.mutation.SetEmail(s)
	return eau
}

// SetUpdatedAt sets the "updated_at" field.
func (eau *EarlyAccessUpdate) SetUpdatedAt(t time.Time) *EarlyAccessUpdate {
	eau.mutation.SetUpdatedAt(t)
	return eau
}

// Mutation returns the EarlyAccessMutation object of the builder.
func (eau *EarlyAccessUpdate) Mutation() *EarlyAccessMutation {
	return eau.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eau *EarlyAccessUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	eau.defaults()
	if len(eau.hooks) == 0 {
		affected, err = eau.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EarlyAccessMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			eau.mutation = mutation
			affected, err = eau.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(eau.hooks) - 1; i >= 0; i-- {
			mut = eau.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, eau.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (eau *EarlyAccessUpdate) SaveX(ctx context.Context) int {
	affected, err := eau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eau *EarlyAccessUpdate) Exec(ctx context.Context) error {
	_, err := eau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eau *EarlyAccessUpdate) ExecX(ctx context.Context) {
	if err := eau.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (eau *EarlyAccessUpdate) defaults() {
	if _, ok := eau.mutation.UpdatedAt(); !ok {
		v := earlyaccess.UpdateDefaultUpdatedAt()
		eau.mutation.SetUpdatedAt(v)
	}
}

func (eau *EarlyAccessUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   earlyaccess.Table,
			Columns: earlyaccess.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: earlyaccess.FieldID,
			},
		},
	}
	if ps := eau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eau.mutation.Email(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: earlyaccess.FieldEmail,
		})
	}
	if value, ok := eau.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: earlyaccess.FieldUpdatedAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{earlyaccess.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// EarlyAccessUpdateOne is the builder for updating a single EarlyAccess entity.
type EarlyAccessUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EarlyAccessMutation
}

// SetEmail sets the "email" field.
func (eauo *EarlyAccessUpdateOne) SetEmail(s string) *EarlyAccessUpdateOne {
	eauo.mutation.SetEmail(s)
	return eauo
}

// SetUpdatedAt sets the "updated_at" field.
func (eauo *EarlyAccessUpdateOne) SetUpdatedAt(t time.Time) *EarlyAccessUpdateOne {
	eauo.mutation.SetUpdatedAt(t)
	return eauo
}

// Mutation returns the EarlyAccessMutation object of the builder.
func (eauo *EarlyAccessUpdateOne) Mutation() *EarlyAccessMutation {
	return eauo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (eauo *EarlyAccessUpdateOne) Select(field string, fields ...string) *EarlyAccessUpdateOne {
	eauo.fields = append([]string{field}, fields...)
	return eauo
}

// Save executes the query and returns the updated EarlyAccess entity.
func (eauo *EarlyAccessUpdateOne) Save(ctx context.Context) (*EarlyAccess, error) {
	var (
		err  error
		node *EarlyAccess
	)
	eauo.defaults()
	if len(eauo.hooks) == 0 {
		node, err = eauo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EarlyAccessMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			eauo.mutation = mutation
			node, err = eauo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(eauo.hooks) - 1; i >= 0; i-- {
			mut = eauo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, eauo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (eauo *EarlyAccessUpdateOne) SaveX(ctx context.Context) *EarlyAccess {
	node, err := eauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (eauo *EarlyAccessUpdateOne) Exec(ctx context.Context) error {
	_, err := eauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eauo *EarlyAccessUpdateOne) ExecX(ctx context.Context) {
	if err := eauo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (eauo *EarlyAccessUpdateOne) defaults() {
	if _, ok := eauo.mutation.UpdatedAt(); !ok {
		v := earlyaccess.UpdateDefaultUpdatedAt()
		eauo.mutation.SetUpdatedAt(v)
	}
}

func (eauo *EarlyAccessUpdateOne) sqlSave(ctx context.Context) (_node *EarlyAccess, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   earlyaccess.Table,
			Columns: earlyaccess.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: earlyaccess.FieldID,
			},
		},
	}
	id, ok := eauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing EarlyAccess.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := eauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, earlyaccess.FieldID)
		for _, f := range fields {
			if !earlyaccess.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != earlyaccess.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := eauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eauo.mutation.Email(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: earlyaccess.FieldEmail,
		})
	}
	if value, ok := eauo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: earlyaccess.FieldUpdatedAt,
		})
	}
	_node = &EarlyAccess{config: eauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, eauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{earlyaccess.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
