// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pepsighan/graftini_backend/internal/pkg/ent/earlyaccess"
	"github.com/pepsighan/graftini_backend/internal/pkg/ent/predicate"
)

// EarlyAccessQuery is the builder for querying EarlyAccess entities.
type EarlyAccessQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.EarlyAccess
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EarlyAccessQuery builder.
func (eaq *EarlyAccessQuery) Where(ps ...predicate.EarlyAccess) *EarlyAccessQuery {
	eaq.predicates = append(eaq.predicates, ps...)
	return eaq
}

// Limit adds a limit step to the query.
func (eaq *EarlyAccessQuery) Limit(limit int) *EarlyAccessQuery {
	eaq.limit = &limit
	return eaq
}

// Offset adds an offset step to the query.
func (eaq *EarlyAccessQuery) Offset(offset int) *EarlyAccessQuery {
	eaq.offset = &offset
	return eaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (eaq *EarlyAccessQuery) Unique(unique bool) *EarlyAccessQuery {
	eaq.unique = &unique
	return eaq
}

// Order adds an order step to the query.
func (eaq *EarlyAccessQuery) Order(o ...OrderFunc) *EarlyAccessQuery {
	eaq.order = append(eaq.order, o...)
	return eaq
}

// First returns the first EarlyAccess entity from the query.
// Returns a *NotFoundError when no EarlyAccess was found.
func (eaq *EarlyAccessQuery) First(ctx context.Context) (*EarlyAccess, error) {
	nodes, err := eaq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{earlyaccess.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (eaq *EarlyAccessQuery) FirstX(ctx context.Context) *EarlyAccess {
	node, err := eaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EarlyAccess ID from the query.
// Returns a *NotFoundError when no EarlyAccess ID was found.
func (eaq *EarlyAccessQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = eaq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{earlyaccess.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (eaq *EarlyAccessQuery) FirstIDX(ctx context.Context) int {
	id, err := eaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EarlyAccess entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one EarlyAccess entity is not found.
// Returns a *NotFoundError when no EarlyAccess entities are found.
func (eaq *EarlyAccessQuery) Only(ctx context.Context) (*EarlyAccess, error) {
	nodes, err := eaq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{earlyaccess.Label}
	default:
		return nil, &NotSingularError{earlyaccess.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (eaq *EarlyAccessQuery) OnlyX(ctx context.Context) *EarlyAccess {
	node, err := eaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EarlyAccess ID in the query.
// Returns a *NotSingularError when exactly one EarlyAccess ID is not found.
// Returns a *NotFoundError when no entities are found.
func (eaq *EarlyAccessQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = eaq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{earlyaccess.Label}
	default:
		err = &NotSingularError{earlyaccess.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (eaq *EarlyAccessQuery) OnlyIDX(ctx context.Context) int {
	id, err := eaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EarlyAccesses.
func (eaq *EarlyAccessQuery) All(ctx context.Context) ([]*EarlyAccess, error) {
	if err := eaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return eaq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (eaq *EarlyAccessQuery) AllX(ctx context.Context) []*EarlyAccess {
	nodes, err := eaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EarlyAccess IDs.
func (eaq *EarlyAccessQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := eaq.Select(earlyaccess.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (eaq *EarlyAccessQuery) IDsX(ctx context.Context) []int {
	ids, err := eaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (eaq *EarlyAccessQuery) Count(ctx context.Context) (int, error) {
	if err := eaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return eaq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (eaq *EarlyAccessQuery) CountX(ctx context.Context) int {
	count, err := eaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (eaq *EarlyAccessQuery) Exist(ctx context.Context) (bool, error) {
	if err := eaq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return eaq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (eaq *EarlyAccessQuery) ExistX(ctx context.Context) bool {
	exist, err := eaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EarlyAccessQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (eaq *EarlyAccessQuery) Clone() *EarlyAccessQuery {
	if eaq == nil {
		return nil
	}
	return &EarlyAccessQuery{
		config:     eaq.config,
		limit:      eaq.limit,
		offset:     eaq.offset,
		order:      append([]OrderFunc{}, eaq.order...),
		predicates: append([]predicate.EarlyAccess{}, eaq.predicates...),
		// clone intermediate query.
		sql:  eaq.sql.Clone(),
		path: eaq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Email string `json:"email,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EarlyAccess.Query().
//		GroupBy(earlyaccess.FieldEmail).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (eaq *EarlyAccessQuery) GroupBy(field string, fields ...string) *EarlyAccessGroupBy {
	group := &EarlyAccessGroupBy{config: eaq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := eaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return eaq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Email string `json:"email,omitempty"`
//	}
//
//	client.EarlyAccess.Query().
//		Select(earlyaccess.FieldEmail).
//		Scan(ctx, &v)
//
func (eaq *EarlyAccessQuery) Select(field string, fields ...string) *EarlyAccessSelect {
	eaq.fields = append([]string{field}, fields...)
	return &EarlyAccessSelect{EarlyAccessQuery: eaq}
}

func (eaq *EarlyAccessQuery) prepareQuery(ctx context.Context) error {
	for _, f := range eaq.fields {
		if !earlyaccess.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if eaq.path != nil {
		prev, err := eaq.path(ctx)
		if err != nil {
			return err
		}
		eaq.sql = prev
	}
	return nil
}

func (eaq *EarlyAccessQuery) sqlAll(ctx context.Context) ([]*EarlyAccess, error) {
	var (
		nodes = []*EarlyAccess{}
		_spec = eaq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &EarlyAccess{config: eaq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, eaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (eaq *EarlyAccessQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := eaq.querySpec()
	return sqlgraph.CountNodes(ctx, eaq.driver, _spec)
}

func (eaq *EarlyAccessQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := eaq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (eaq *EarlyAccessQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   earlyaccess.Table,
			Columns: earlyaccess.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: earlyaccess.FieldID,
			},
		},
		From:   eaq.sql,
		Unique: true,
	}
	if unique := eaq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := eaq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, earlyaccess.FieldID)
		for i := range fields {
			if fields[i] != earlyaccess.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := eaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := eaq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := eaq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := eaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (eaq *EarlyAccessQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(eaq.driver.Dialect())
	t1 := builder.Table(earlyaccess.Table)
	selector := builder.Select(t1.Columns(earlyaccess.Columns...)...).From(t1)
	if eaq.sql != nil {
		selector = eaq.sql
		selector.Select(selector.Columns(earlyaccess.Columns...)...)
	}
	for _, p := range eaq.predicates {
		p(selector)
	}
	for _, p := range eaq.order {
		p(selector)
	}
	if offset := eaq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := eaq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EarlyAccessGroupBy is the group-by builder for EarlyAccess entities.
type EarlyAccessGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (eagb *EarlyAccessGroupBy) Aggregate(fns ...AggregateFunc) *EarlyAccessGroupBy {
	eagb.fns = append(eagb.fns, fns...)
	return eagb
}

// Scan applies the group-by query and scans the result into the given value.
func (eagb *EarlyAccessGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := eagb.path(ctx)
	if err != nil {
		return err
	}
	eagb.sql = query
	return eagb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (eagb *EarlyAccessGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := eagb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (eagb *EarlyAccessGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(eagb.fields) > 1 {
		return nil, errors.New("ent: EarlyAccessGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := eagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (eagb *EarlyAccessGroupBy) StringsX(ctx context.Context) []string {
	v, err := eagb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (eagb *EarlyAccessGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = eagb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{earlyaccess.Label}
	default:
		err = fmt.Errorf("ent: EarlyAccessGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (eagb *EarlyAccessGroupBy) StringX(ctx context.Context) string {
	v, err := eagb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (eagb *EarlyAccessGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(eagb.fields) > 1 {
		return nil, errors.New("ent: EarlyAccessGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := eagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (eagb *EarlyAccessGroupBy) IntsX(ctx context.Context) []int {
	v, err := eagb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (eagb *EarlyAccessGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = eagb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{earlyaccess.Label}
	default:
		err = fmt.Errorf("ent: EarlyAccessGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (eagb *EarlyAccessGroupBy) IntX(ctx context.Context) int {
	v, err := eagb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (eagb *EarlyAccessGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(eagb.fields) > 1 {
		return nil, errors.New("ent: EarlyAccessGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := eagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (eagb *EarlyAccessGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := eagb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (eagb *EarlyAccessGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = eagb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{earlyaccess.Label}
	default:
		err = fmt.Errorf("ent: EarlyAccessGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (eagb *EarlyAccessGroupBy) Float64X(ctx context.Context) float64 {
	v, err := eagb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (eagb *EarlyAccessGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(eagb.fields) > 1 {
		return nil, errors.New("ent: EarlyAccessGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := eagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (eagb *EarlyAccessGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := eagb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (eagb *EarlyAccessGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = eagb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{earlyaccess.Label}
	default:
		err = fmt.Errorf("ent: EarlyAccessGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (eagb *EarlyAccessGroupBy) BoolX(ctx context.Context) bool {
	v, err := eagb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (eagb *EarlyAccessGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range eagb.fields {
		if !earlyaccess.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := eagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (eagb *EarlyAccessGroupBy) sqlQuery() *sql.Selector {
	selector := eagb.sql
	columns := make([]string, 0, len(eagb.fields)+len(eagb.fns))
	columns = append(columns, eagb.fields...)
	for _, fn := range eagb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(eagb.fields...)
}

// EarlyAccessSelect is the builder for selecting fields of EarlyAccess entities.
type EarlyAccessSelect struct {
	*EarlyAccessQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (eas *EarlyAccessSelect) Scan(ctx context.Context, v interface{}) error {
	if err := eas.prepareQuery(ctx); err != nil {
		return err
	}
	eas.sql = eas.EarlyAccessQuery.sqlQuery(ctx)
	return eas.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (eas *EarlyAccessSelect) ScanX(ctx context.Context, v interface{}) {
	if err := eas.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (eas *EarlyAccessSelect) Strings(ctx context.Context) ([]string, error) {
	if len(eas.fields) > 1 {
		return nil, errors.New("ent: EarlyAccessSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := eas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (eas *EarlyAccessSelect) StringsX(ctx context.Context) []string {
	v, err := eas.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (eas *EarlyAccessSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = eas.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{earlyaccess.Label}
	default:
		err = fmt.Errorf("ent: EarlyAccessSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (eas *EarlyAccessSelect) StringX(ctx context.Context) string {
	v, err := eas.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (eas *EarlyAccessSelect) Ints(ctx context.Context) ([]int, error) {
	if len(eas.fields) > 1 {
		return nil, errors.New("ent: EarlyAccessSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := eas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (eas *EarlyAccessSelect) IntsX(ctx context.Context) []int {
	v, err := eas.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (eas *EarlyAccessSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = eas.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{earlyaccess.Label}
	default:
		err = fmt.Errorf("ent: EarlyAccessSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (eas *EarlyAccessSelect) IntX(ctx context.Context) int {
	v, err := eas.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (eas *EarlyAccessSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(eas.fields) > 1 {
		return nil, errors.New("ent: EarlyAccessSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := eas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (eas *EarlyAccessSelect) Float64sX(ctx context.Context) []float64 {
	v, err := eas.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (eas *EarlyAccessSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = eas.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{earlyaccess.Label}
	default:
		err = fmt.Errorf("ent: EarlyAccessSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (eas *EarlyAccessSelect) Float64X(ctx context.Context) float64 {
	v, err := eas.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (eas *EarlyAccessSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(eas.fields) > 1 {
		return nil, errors.New("ent: EarlyAccessSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := eas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (eas *EarlyAccessSelect) BoolsX(ctx context.Context) []bool {
	v, err := eas.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (eas *EarlyAccessSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = eas.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{earlyaccess.Label}
	default:
		err = fmt.Errorf("ent: EarlyAccessSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (eas *EarlyAccessSelect) BoolX(ctx context.Context) bool {
	v, err := eas.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (eas *EarlyAccessSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := eas.sqlQuery().Query()
	if err := eas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (eas *EarlyAccessSelect) sqlQuery() sql.Querier {
	selector := eas.sql
	selector.Select(selector.Columns(eas.fields...)...)
	return selector
}
