// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/pepsighan/graftini_backend/internal/pkg/ent/graphqlquery"
	"github.com/pepsighan/graftini_backend/internal/pkg/ent/predicate"
)

// GraphQLQueryDelete is the builder for deleting a GraphQLQuery entity.
type GraphQLQueryDelete struct {
	config
	hooks    []Hook
	mutation *GraphQLQueryMutation
}

// Where adds a new predicate to the GraphQLQueryDelete builder.
func (gqqd *GraphQLQueryDelete) Where(ps ...predicate.GraphQLQuery) *GraphQLQueryDelete {
	gqqd.mutation.predicates = append(gqqd.mutation.predicates, ps...)
	return gqqd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gqqd *GraphQLQueryDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(gqqd.hooks) == 0 {
		affected, err = gqqd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GraphQLQueryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gqqd.mutation = mutation
			affected, err = gqqd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(gqqd.hooks) - 1; i >= 0; i-- {
			mut = gqqd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gqqd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (gqqd *GraphQLQueryDelete) ExecX(ctx context.Context) int {
	n, err := gqqd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gqqd *GraphQLQueryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: graphqlquery.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: graphqlquery.FieldID,
			},
		},
	}
	if ps := gqqd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, gqqd.driver, _spec)
}

// GraphQLQueryDeleteOne is the builder for deleting a single GraphQLQuery entity.
type GraphQLQueryDeleteOne struct {
	gqqd *GraphQLQueryDelete
}

// Exec executes the deletion query.
func (gqqdo *GraphQLQueryDeleteOne) Exec(ctx context.Context) error {
	n, err := gqqdo.gqqd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{graphqlquery.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gqqdo *GraphQLQueryDeleteOne) ExecX(ctx context.Context) {
	gqqdo.gqqd.ExecX(ctx)
}
