// Code generated by qtc from "pageContent.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Generates the React markup for the page based on the component map.
//

//line templates/pageContent.qtpl:3
package templates

//line templates/pageContent.qtpl:3
import "github.com/pepsighan/graftini_backend/ent/schema"

//line templates/pageContent.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/pageContent.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/pageContent.qtpl:5
func StreamPageContent(qw422016 *qt422016.Writer, m *schema.ComponentMap) {
//line templates/pageContent.qtpl:5
	qw422016.N().S(`
return (
  <>
    Hello World
  </>
);
`)
//line templates/pageContent.qtpl:11
}

//line templates/pageContent.qtpl:11
func WritePageContent(qq422016 qtio422016.Writer, m *schema.ComponentMap) {
//line templates/pageContent.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/pageContent.qtpl:11
	StreamPageContent(qw422016, m)
//line templates/pageContent.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line templates/pageContent.qtpl:11
}

//line templates/pageContent.qtpl:11
func PageContent(m *schema.ComponentMap) string {
//line templates/pageContent.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/pageContent.qtpl:11
	WritePageContent(qb422016, m)
//line templates/pageContent.qtpl:11
	qs422016 := string(qb422016.B)
//line templates/pageContent.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/pageContent.qtpl:11
	return qs422016
//line templates/pageContent.qtpl:11
}
