// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPage struct {
	ProjectID int    `json:"projectId"`
	Name      string `json:"name"`
	Route     string `json:"route"`
}

type NewProject struct {
	Name string `json:"name"`
}
