// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Deployment is the predicate function for deployment builders.
type Deployment func(*sql.Selector)

// EarlyAccess is the predicate function for earlyaccess builders.
type EarlyAccess func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// GraphQLQuery is the predicate function for graphqlquery builders.
type GraphQLQuery func(*sql.Selector)

// Page is the predicate function for page builders.
type Page func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
