// Code generated by qtc from "pageContent.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/pageContent.qtpl:1
package templates

//line templates/pageContent.qtpl:1
import "github.com/pepsighan/graftini_backend/internal/pkg/ent/schema"

//line templates/pageContent.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/pageContent.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/pageContent.qtpl:4
func StreamPageContent(qw422016 *qt422016.Writer, m schema.ComponentMap) {
//line templates/pageContent.qtpl:4
	qw422016.N().S(`
return (
  `)
//line templates/pageContent.qtpl:6
	streamrootContent(qw422016, m)
//line templates/pageContent.qtpl:6
	qw422016.N().S(`
);
`)
//line templates/pageContent.qtpl:8
}

//line templates/pageContent.qtpl:8
func WritePageContent(qq422016 qtio422016.Writer, m schema.ComponentMap) {
//line templates/pageContent.qtpl:8
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/pageContent.qtpl:8
	StreamPageContent(qw422016, m)
//line templates/pageContent.qtpl:8
	qt422016.ReleaseWriter(qw422016)
//line templates/pageContent.qtpl:8
}

//line templates/pageContent.qtpl:8
func PageContent(m schema.ComponentMap) string {
//line templates/pageContent.qtpl:8
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/pageContent.qtpl:8
	WritePageContent(qb422016, m)
//line templates/pageContent.qtpl:8
	qs422016 := string(qb422016.B)
//line templates/pageContent.qtpl:8
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/pageContent.qtpl:8
	return qs422016
//line templates/pageContent.qtpl:8
}

//line templates/pageContent.qtpl:12
func streamrootContent(qw422016 *qt422016.Writer, m schema.ComponentMap) {
//line templates/pageContent.qtpl:12
	qw422016.N().S(`
  <>
    `)
//line templates/pageContent.qtpl:14
	for _, childID := range m["ROOT"].ChildrenNodes {
//line templates/pageContent.qtpl:14
		qw422016.N().S(`
      `)
//line templates/pageContent.qtpl:15
		streamsubPageContent(qw422016, childID, m)
//line templates/pageContent.qtpl:15
		qw422016.N().S(`
    `)
//line templates/pageContent.qtpl:16
	}
//line templates/pageContent.qtpl:16
	qw422016.N().S(`
  </>
`)
//line templates/pageContent.qtpl:18
}

//line templates/pageContent.qtpl:18
func writerootContent(qq422016 qtio422016.Writer, m schema.ComponentMap) {
//line templates/pageContent.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/pageContent.qtpl:18
	streamrootContent(qw422016, m)
//line templates/pageContent.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line templates/pageContent.qtpl:18
}

//line templates/pageContent.qtpl:18
func rootContent(m schema.ComponentMap) string {
//line templates/pageContent.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/pageContent.qtpl:18
	writerootContent(qb422016, m)
//line templates/pageContent.qtpl:18
	qs422016 := string(qb422016.B)
//line templates/pageContent.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/pageContent.qtpl:18
	return qs422016
//line templates/pageContent.qtpl:18
}

//line templates/pageContent.qtpl:23
func streamsubPageContent(qw422016 *qt422016.Writer, id string, m schema.ComponentMap) {
//line templates/pageContent.qtpl:23
	qw422016.N().S(`
  <`)
//line templates/pageContent.qtpl:24
	qw422016.E().V(m[id].Type)
//line templates/pageContent.qtpl:24
	qw422016.N().S(`>
    `)
//line templates/pageContent.qtpl:25
	if m[id].IsCanvas == true {
//line templates/pageContent.qtpl:25
		qw422016.N().S(`
      `)
//line templates/pageContent.qtpl:26
		for _, childID := range m[id].ChildrenNodes {
//line templates/pageContent.qtpl:26
			qw422016.N().S(`
        `)
//line templates/pageContent.qtpl:27
			streamsubPageContent(qw422016, childID, m)
//line templates/pageContent.qtpl:27
			qw422016.N().S(`
      `)
//line templates/pageContent.qtpl:28
		}
//line templates/pageContent.qtpl:28
		qw422016.N().S(`
    `)
//line templates/pageContent.qtpl:29
	}
//line templates/pageContent.qtpl:29
	qw422016.N().S(`
  </`)
//line templates/pageContent.qtpl:30
	qw422016.E().V(m[id].Type)
//line templates/pageContent.qtpl:30
	qw422016.N().S(`>
`)
//line templates/pageContent.qtpl:31
}

//line templates/pageContent.qtpl:31
func writesubPageContent(qq422016 qtio422016.Writer, id string, m schema.ComponentMap) {
//line templates/pageContent.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/pageContent.qtpl:31
	streamsubPageContent(qw422016, id, m)
//line templates/pageContent.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line templates/pageContent.qtpl:31
}

//line templates/pageContent.qtpl:31
func subPageContent(id string, m schema.ComponentMap) string {
//line templates/pageContent.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/pageContent.qtpl:31
	writesubPageContent(qb422016, id, m)
//line templates/pageContent.qtpl:31
	qs422016 := string(qb422016.B)
//line templates/pageContent.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/pageContent.qtpl:31
	return qs422016
//line templates/pageContent.qtpl:31
}
