// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GraphQLQuery is the predicate function for graphqlquery builders.
type GraphQLQuery func(*sql.Selector)

// Page is the predicate function for page builders.
type Page func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
